language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
global:
  env:
  - PIN=opam-lib:https://github.com/samoht/opam.git
  matrix:
  - OCAML_VERSION=3.12
  - OCAML_VERSION=4.00
  - OCAML_VERSION=4.01
  - OCAML_VERSION=4.02
