language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - EXTRA_REMOTES="https://github.com/samoht/ciso-repo.git"
    - PACKAGE=ciso
  matrix:
    - OCAML_VERSION=4.01
    - OCAML_VERSION=4.02
